# default properties
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: selfsigned_authuserkeystore
    key-store-password: f00B4r@gmol.org
    key-store: classpath:ssl-rest-authusers.pfx
    key-store-provider: SUN
    key-store-type: PKCS12
    key-password: f00B4r@gmol.org
  http2:
    enabled: true

app:
  name: user-auth
  dir: ${user.home}/.${app.name}
  db-name: authusers
  db-host: localhost
  db-port: 5432
  db-url-prefix: jdbc:postgresql://
  db-username: postgres
  db-password: postgres
  jwt-secret: cp*D33tZY(juumBUcBDVv8tJ!8w/T@JGpS)@)Sr6EYfjFBTRUJfu@&6jz-7*cFk5
  signin-path-patterns:
    - /v1/jwt/authenticate
    - /v1/auth/signin
  public-path-patterns:
    - /v1/jwt/ispublic
    - /v1/jwt/register
    - /v1/public
  ignore-path-patterns:
    - /resources/**

spring:  
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
    initialization-mode: never

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      show_sql: true
      use_sql_comments: true
      generate_statistics: false

  flyway:
    enabled: true
    baseline-on-migrate: true
