# default properties
server:
  port: 5050

app:
  name: user-auth
  dir: ${user.home}/.${app.name}
  db:
    name: authusers
    host: localhost
    postgres:
      url:
        prefix: jdbc:postgresql://
        port: 5432

spring:  
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db.postgres.url.prefix}${app.db.host}:${app.db.postgres.url.port}/${app.db.name}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
      show_sql: true
      use_sql_comments: true
      generate_statistics: false



  