# default properties
server:
  port: 9090

app:
  name: user-auth
  dir: ${user.home}/.${app.name}
  host: localhost
  uri-scheme: http
  db-name: authusers
  db-host: ${app.host}
  db-port: 5432
  db-url-prefix: jdbc:postgresql://
  db-username: postgres
  db-password: postgres
  context-path: ${app.uri-scheme}://${app.host}:${server.port}/
  signin-failed-page: unauthorized.html
  jwt:
    secret: cp*D33tZY(juumBUcBDVv8tJ!8w/T@JGpS)@)Sr6EYfjFBTRUJfu@&6jz-7*cFk5
  signin-path-patterns:
    - /v1/auth/signin
  public-path-patterns:
    - /v1/auth/authenticate
    - /v1/auth/signup
    - /v1/jwt/ispublic
    - /v1/jwt/register
    - /v1/public
  ignore-path-patterns:
    - /resources/**
    - /v1/jwt/register
    - /v1/jwt/unauthorized
    - /v2/api-docs # swagger ui
    - /configuration/ui # swagger ui
    - /swagger-resources/** # swagger ui
    - /configuration/security # swagger ui
    - /swagger-ui.html # swagger ui
    - /webjars/** # swagger ui

spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
    initialization-mode: never

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      show_sql: true
      use_sql_comments: true
      generate_statistics: false

  flyway:
    enabled: true
    baseline-on-migrate: true
