GET https://localhost:8443/v1/jwt/private
Authorization: Bearer eyJ0b2tlbi10eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJpc3MiOiJ1c2VyLWF1dGgtYXBpIiwiYXVkIjoidXNlci1hdXRoLWFwcCIsInN1YiI6ImZvbyIsImV4cCI6MTU5NDEzMDkwNCwidS1yb2xlcyI6WyJwZXJtaXNzaW9uOmRlbGV0ZV9maWxlcyIsInBlcm1pc3Npb246bW9kaWZ5X2ZpbGVzIiwicm9sZTpyb290IiwicGVybWlzc2lvbjp2aWV3X3VzZXIiLCJwZXJtaXNzaW9uOnVwZGF0ZV91c2VyIiwicGVybWlzc2lvbjp2aWV3X2ZpbGVzIiwicGVybWlzc2lvbjpjcmVhdGVfZmlsZXMiLCJwZXJtaXNzaW9uOmNyZWF0ZV91c2VyIiwicGVybWlzc2lvbjpkZWxldGVfdXNlciJdfQ.qRjvSTC1ccikI63MCXrk7CryrBLxWUpVkMZUW67BC6KY8K_cUEpXRg17jKCn-DztLHa6gmdba9ULdBc6rv9WXw
Accept: application/json
Content-Type: application/json
